version: '3.0'
services:
  db:
    image: mariadb:latest
    ports:
      - '3306:3306'
    volumes:
      - dbvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  website:
    depends_on:
      - 'db'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./config/credentials/production.key:/app/config/credentials/production.key
      - ./config/credentials/production.yml.enc:/app/config/credentials/production.yml.enc
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      EMAIL_HOST: ${EMAIL_HOST}


volumes:
  dbvol: